
export type MenuSettings = {
	backgroundColor: number,
	foregroundColor: number,
	titleFontSize: number,
	padding: number,
	borderColor: number,
	borderThickness: number,
	borderAlpha: number,
	windowAlpha: number,
	font: string,
	fps: number,
	characterListSpacing: number,
	characterListMargin: number,
	characterListPadding: number,
	characterItemPadding: number,
	characterFontSize: number,
	itemListWidth: number,
	itemListMargin: number,
	itemListPadding: number,
	itemColor: number,
	itemSelectColor: number,
	itemDisabledColor: number,
	itemSpacing: number,
	itemFontSize: number,
	actionKey: string,
	upKey: string,
	downKey: string,
};